<?php ?>
<script type="text/javascript">
    function kdt_id() {
        var visitor_id = getKondutoID();

        var cname = 'score_visiter_id';
        var cvalue = visitor_id;
        var exdays = 1;

        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toGMTString();
        document.cookie = cname + "=" + cvalue + "; " + expires;
    }
    Event.observe(window, "load", kdt_id);

</script>